export enum DbQueryNodes {
  GetTables = 'get_tables',
  GetColumns = 'get_columns',
  CheckPermissions = 'check_permissions',
  SqlGeneration = 'sql_generation',
  SyntacticValidator = 'syntactic_validator',
  SemanticValidator = 'semantic_validator',
  IsImprovement = 'is_improvement',
  Failed = 'failed',
  SaveDataset = 'save_dataset',
  CheckCache = 'check_cache',
  PostCacheAndTables = 'post_cache_and_tables',
  GenerateChecklist = 'generate_checklist',
  GenerateDescription = 'generate_description',
  VerifyChecklist = 'verify_checklist',
  PreValidation = 'pre_validation',
  PostValidation = 'post_validation',
  ClassifyChange = 'classify_change',
  FixQuery = 'fix_query',
}
