import {AnyObject} from '@loopback/repository';
import {ChangeType, DatabaseSchema, Status} from './types';

/**
 * State shape threaded through every step of the Mastra DbQuery workflow.
 * Previously generated by `@langchain/langgraph` `Annotation.Root()` —
 * rewritten as a plain TypeScript interface with zero LangGraph dependency.
 */
export interface DbQueryState {
  prompt: string;
  schema: DatabaseSchema;
  sql?: string;
  status?: Status;
  id?: string;
  feedbacks?: string[];
  replyToUser?: string;
  datasetId?: string;
  sampleSqlPrompt?: string;
  sampleSql?: string;
  fromCache?: boolean;
  done?: boolean;
  resultArray?: AnyObject[string][];
  description?: string;
  directCall?: boolean;
  validationChecklist?: string;
  syntacticStatus?: Status;
  syntacticFeedback?: string;
  semanticStatus?: Status;
  semanticFeedback?: string;
  syntacticErrorTables?: string[];
  semanticErrorTables?: string[];
  changeType?: ChangeType;
  fromTemplate?: boolean;
  templateId?: string;
}
