import {AnyObject} from '@loopback/repository';
import {IVisualizer} from './types';

/**
 * State shape threaded through every step of the Mastra Visualization workflow.
 * Previously generated by `@langchain/langgraph` `Annotation.Root()` —
 * rewritten as a plain TypeScript interface with zero LangGraph dependency.
 */
export interface VisualizationGraphState {
  prompt: string;
  datasetId: string;
  sql?: string;
  queryDescription?: string;
  visualizer?: IVisualizer;
  visualizerName?: string;
  done?: boolean;
  visualizerConfig?: AnyObject;
  error?: string;
  type?: string;
}
