export const TOOL_TAG = 'isTOOL';
export const TOOL_NAME = 'TOOL';
export const GRAPH_NODE_TAG = 'isNODE';
export const GRAPH_NODE_NAME = 'GRAPH_NODE';
export const DEFAULT_MAX_TOKEN_COUNT = 8192;
export const MB = 1024 * 1024; // 1 MB in bytes
const FIVE = 5;
const TWENTY = 20;
export const DEFAULT_FILE_SIZE = FIVE * MB;
export const MAX_TOTAL_SIZE = TWENTY * MB;
export const MAX_CONSTRAINT_NAME_LENGTH = 63; // PostgreSQL limit for constraint names
export const CHAT_TITLE_MAX_LENGTH = 200; // Maximum length for chat title
